# ===============================
# APLICACION
# ===============================
spring.application.name=bank-api

server.port=8080

spring.data.web.page-serialization-mode=via_dto

# ===============================
# BASE DE DATOS MYSQL
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/bankdb?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=bank
spring.datasource.password=bank123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===============================
# LOGGING
# ===============================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE


# ===============================
# JWT
# ===============================
app.jwt.secret=ZnJhbmNvc3BpbmV0aWJidmFqdWxpbzIwMjYxMjM0NTY=